FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build-env
ENV CONNECTIONSTRING: ""
ENV REMOTEHOST: ""
ENV REMOTEPORT: ""

WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim
WORKDIR /app
COPY --from=build-env /app/out ./

ENTRYPOINT ["dotnet", "DeviceProxy.dll"]